name: Example workflow using Bearer

on:
  push:
    branches:
      - main

permissions:
  contents: read # Minimal permissions

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bearer
        uses: bearer/actions@main
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          BEARER_HOST: my.staging.bearer.sh
          DEBUG: 1